version: "3"
services:
  db:
    image: mysql:8.0.23
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3302:3302"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql
  api:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/docker-ruby-template
      - api-data:/docker-ruby-template/vendor/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  api-data:
  mysql-data:
    driver: local
